#!/bin/bash
#
#   Unit: oneapi-variants
#   Description:
#       This unit creates an intel module that points to the current hybrid
#       OneAPI setup (icx/icpx/ifort). This unit will be removed once the
#       classic Intel compilers are fully extinct.
#
#   Author:         Brian Vanderwende
#   Last Revised:   16:13, 15 Nov 2024
#

tsecho "Populating Intel compiler module set"
cd $MOD_DEPLOYMENT

if [[ -d Core/intel-oneapi ]]; then
    mkdir -p Core/intel

    for icver in $(find Core/intel-oneapi/ -type f); do
        sed '/INTEL_COMPILER_TYPE/ s/ONEAPI/RECOMMENDED/' $icver > $TMP_FILE
        
        if [[ $(sed 's|.*/\([^.]*\).*|\1|' <<< $icver) -ge 2024 ]]; then
            sed -i 's|\([/"]\)ifx|\1ifort|' $TMP_FILE
        else
            sed -i 's|/ifx|/intel64/ifort|' $TMP_FILE
            sed -i 's|ifx|ifort|' $TMP_FILE
        fi

        mv $TMP_FILE ${icver/-oneapi}
    done

    if [[ -f Core/intel-oneapi/default ]]; then
        def_imod=$(basename $(readlink -f Core/intel-oneapi/default))
        ln -sfn $def_imod Core/intel/default
    fi
fi

if [[ -d Core/intel-classic ]]; then
    for icver in $(find Core/intel-classic/ -type f); do
        ccver=$(sed -n '/INTEL_VERSION/ s|.*"\(.*\)".*|\1|p' $icver)
        onever=$(sed 's|.*/\(.*\)\.lua|\1|' <<< $icver)

        sed -i "/MODULEPATH/ s|intel|oneapi|" $icver
        sed -i "/MODULEPATH/ s|${ccver}|${onever}|" $icver
    done
fi
