compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: sles15
    target: x86_64
    spec: gcc@7.5.0
    modules: []
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/icc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/icpc
      f77: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/ifort
      fc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/ifort
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/compiler/lib/intel64
- compiler:
    spec: oneapi@2022.1.0
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/ifx
      fc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/ifx
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/compiler/lib/intel64
- compiler:
    spec: intel@2021.7.1
    paths:
      cc: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/intel64/icc
      cxx: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/intel64/icpc
      f77: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/intel64/ifort
      fc: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/intel64/ifort
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/compiler/lib/intel64
- compiler:
    spec: oneapi@2022.2.1
    paths:
      cc: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/ifx
      fc: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/bin/ifx
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.12/spack/opt/spack/intel-oneapi-compilers/2022.2.1/compiler/latest/linux/compiler/lib/intel64
- compiler:
    spec: nvhpc@21.3
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/lib
- compiler:
    spec: nvhpc@22.2
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/lib
- compiler:
    spec: nvhpc@22.7
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/lib
- compiler:
    spec: nvhpc@22.9
    paths:
      cc: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.9/Linux_x86_64/22.9/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.9/Linux_x86_64/22.9/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.9/Linux_x86_64/22.9/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.9/Linux_x86_64/22.9/compilers/bin/nvfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.9/Linux_x86_64/22.9/compilers/lib
- compiler:
    spec: nvhpc@22.11
    paths:
      cc: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.11/Linux_x86_64/22.11/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.11/Linux_x86_64/22.11/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.11/Linux_x86_64/22.11/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.11/Linux_x86_64/22.11/compilers/bin/nvfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.12/spack/opt/spack/nvhpc/22.11/Linux_x86_64/22.11/compilers/lib
- compiler:
    spec: cce@14.0.2
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - cce/14.0.2
    environment:
      set:
        PE_ENV: CRAY
- compiler:
    spec: cce@14.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - cce/14.0.3
    environment:
      set:
        PE_ENV: CRAY
- compiler:
    spec: cce@15.0.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - cce/15.0.0
    environment:
      set:
        PE_ENV: CRAY
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - gcc/10.3.0
    environment:
      set:
        PE_ENV: GNU
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - gcc/11.2.0
    environment:
      set:
        PE_ENV: GNU
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - craype
    - gcc/12.1.0
    environment:
      set:
        PE_ENV: GNU
