compilers:
- compiler:
    spec: gcc@12.4.0
    paths:
      cc: /glade/u/apps/gust/24.12/spack/opt/spack//gcc/12.4.0/skuh/bin/gcc
      cxx: /glade/u/apps/gust/24.12/spack/opt/spack//gcc/12.4.0/skuh/bin/g++
      f77: /glade/u/apps/gust/24.12/spack/opt/spack//gcc/12.4.0/skuh/bin/gfortran
      fc: /glade/u/apps/gust/24.12/spack/opt/spack//gcc/12.4.0/skuh/bin/gfortran
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
- compiler:
    spec: nvhpc@24.11
    paths:
      cc: /glade/u/apps/gust/24.12/spack/opt/spack//nvhpc/24.11/gcc/12.4.0/7hya/Linux_x86_64/24.11/compilers/bin/nvc
      cxx: /glade/u/apps/gust/24.12/spack/opt/spack//nvhpc/24.11/gcc/12.4.0/7hya/Linux_x86_64/24.11/compilers/bin/nvc++
      f77: /glade/u/apps/gust/24.12/spack/opt/spack//nvhpc/24.11/gcc/12.4.0/7hya/Linux_x86_64/24.11/compilers/bin/nvfortran
      fc: /glade/u/apps/gust/24.12/spack/opt/spack//nvhpc/24.11/gcc/12.4.0/7hya/Linux_x86_64/24.11/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/gust/24.12/spack/opt/spack//nvhpc/24.11/gcc/12.4.0/7hya/Linux_x86_64/24.11/compilers/lib
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2024.2.1/gcc/12.4.0/kozc/compiler/latest/bin/icx
      cxx: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2024.2.1/gcc/12.4.0/kozc/compiler/latest/bin/icpx
      f77: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2024.2.1/gcc/12.4.0/kozc/compiler/latest/bin/ifx
      fc: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2024.2.1/gcc/12.4.0/kozc/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
- compiler:
    spec: oneapi@2025.0.3
    paths:
      cc: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2025.0.3/gcc/12.4.0/cffk/compiler/latest/bin/icx
      cxx: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2025.0.3/gcc/12.4.0/cffk/compiler/latest/bin/icpx
      f77: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2025.0.3/gcc/12.4.0/cffk/compiler/latest/bin/ifx
      fc: /glade/u/apps/gust/24.12/spack/opt/spack//intel-oneapi-compilers/2025.0.3/gcc/12.4.0/cffk/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
- compiler:
    spec: cce@18.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - cce/18.0.1
    environment:
      set:
        PE_ENV: CRAY
        CRAY_CPU_TARGET: x86-milan
        NVCCFLAGS: -allow-unsupported-compiler
        NVCC_PREPEND_FLAGS: -allow-unsupported-compiler
        # These are needed for kokkos (see kokkos_check_env.cmake)
        CRAYPE_VERSION: 1
        CRAYPE_LINK_TYPE: dynamic
      append_path:
        LD_LIBRARY_PATH: /glade/u/apps/gust/24.12/spack/opt/spack/_spack_path_placeholder__/__spack/gcc/12.4.0/skuh/lib64
        LIBRARY_PATH: /glade/u/apps/gust/24.12/spack/opt/spack//gcc/12.4.0/skuh/lib64
