compilers:
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: nvhpc@24.1
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvc++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/bin/nvfortran
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1/Linux_x86_64/24.1/compilers/lib
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: oneapi@2024.0.2
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/icx
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/icpx
      f77: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/ifx
      fc: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2/compiler/latest/bin/ifx
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: gcc@13.2.0
    paths:
      cc: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gcc
      cxx: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/g++
      f77: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gfortran
      fc: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gfortran
    operating_system: sles15
    modules: []
    environment:
      set:
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
- compiler:
    spec: cce@16.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    modules:
    - craype
    - cce/16.0.1
    environment:
      set:
        PE_ENV: CRAY
        NVCCFLAGS: -allow-unsupported-compiler
      append_path:
        LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64
