compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
    flags: {}
    spec: gcc@7.5.0
- compiler:
    spec: intel@2021.6.0
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/icc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/icpc
      f77: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/ifort
      fc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/intel64/ifort
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        PE_ENV: INTEL
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/compiler/lib/intel64
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: oneapi@2022.1.0
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/icx
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/icpx
      f77: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/ifx
      fc: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/intel-oneapi-compilers/2022.1.0/gcc/7.5.0/compiler/latest/linux/compiler/lib/intel64
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: nvhpc@21.3
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        NVLOCALRC: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/localrc/gust
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/21.3/gcc/7.5.0/Linux_x86_64/21.3/compilers/lib
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: nvhpc@22.2
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        NVLOCALRC: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/localrc/gust
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.2/gcc/7.5.0/Linux_x86_64/22.2/compilers/lib
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: nvhpc@22.7
    paths:
      cc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvc
      cxx: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvc++
      f77: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvfortran
      fc: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/bin/nvfortran
    flags: {}
    operating_system: sles15
    target: x86_64
    modules: []
    environment:
      set:
        NVLOCALRC: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/localrc/gust
      prepend_path:
        LD_LIBRARY_PATH: /glade/u/apps/common/22.08/spack/opt/spack/nvhpc/22.7/gcc/7.5.0/Linux_x86_64/22.7/compilers/lib
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: cce@14.0.2
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - cce/14.0.2
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: cce@14.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray/8.3.3
    - cce/14.0.3
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/10.3.0
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
- compiler:
    spec: gcc@12.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu/8.3.3
    - gcc/12.1.0
    environment:
      prepend_path:
        CPATH: /glade/u/apps/common/22.08/opt/include
        LIBRARY_PATH: /glade/u/apps/common/22.08/opt/lib64:/glade/u/apps/common/22.08/opt/lib
    extra_rpaths:
    - /glade/u/apps/common/22.08/opt/lib64
    - /glade/u/apps/common/22.08/opt/lib
