config:
  install_tree:
    projections:
      gcc: '{name}/{version}'
      hdf5+threadsafe: '{name}/{version}-safe/{compiler.name}/{compiler.version}'
      netcdf-c^hdf5+threadsafe: '{name}/{version}-safe/{compiler.name}/{compiler.version}'
      eccodes^hdf5+threadsafe: '{name}/{version}-safe/{compiler.name}/{compiler.version}'
      all: '{name}/{version}/{compiler.name}/{compiler.version}'
      ^mpi: '{name}/{version}/{compiler.name}/{compiler.version}/{^mpi.name}/{^mpi.version}'
  build_jobs: 8
  test_stage: /glade/gust/scratch/csgteam/temp/spack/tests
  source_cache: /glade/gust/scratch/csgteam/temp/spack/cache
  build_stage:
  - /glade/gust/scratch/csgteam/temp/spack/builds
  template_dirs:
  - /glade/work/csgteam/spack-deployments/gust/22.08b/envs/build/templates/modules
