config:
  install_tree:
    projections:
      ^mpi: '{name}/{version}/{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/{hash:4}'
      all: '{name}/{version}/{compiler.name}/{compiler.version}/{hash:4}'
      gcc: '{name}/{version}/{hash:4}'
      netcdf-c: netcdf/{version}/packages/{name}/{version}/{compiler.name}/{compiler.version}/{hash:4}
      netcdf-c^mpi: netcdf/{version}/packages/{name}/{version}/{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/{hash:4}
      netcdf-cxx4: netcdf/{^netcdf-c.version}/packages/{name}/{version}/{compiler.name}/{compiler.version}/{hash:4}
      netcdf-cxx4^mpi: netcdf/{^netcdf-c.version}/packages/{name}/{version}/{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/{hash:4}
      netcdf-fortran: netcdf/{^netcdf-c.version}/packages/{name}/{version}/{compiler.name}/{compiler.version}/{hash:4}
      netcdf-fortran^mpi: netcdf/{^netcdf-c.version}/packages/{name}/{version}/{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/{hash:4}
  build_jobs: 4
  test_stage: /localfs/spack-cache/gust/24.12/tests
  source_cache: /localfs/spack-cache/cache
  misc_cache: /localfs/spack-cache/gust/24.12/misc
  build_stage:
  - /localfs/spack-cache/gust/24.12/builds
  shared_linking:
  # Turning bind setting on would be beneficial but vendor compilers do not
  # seem to work with it! Avoid!
    type: rpath
    bind: false
  template_dirs:
  - /glade/u/apps/gust/24.12/envs/build/templates/modules
