mirrors:
  ncar_mirror_global:
    fetch:
      url: file:///glade/u/apps/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///glade/u/apps/mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
