packages:
  gcc:
    externals:
    - spec: gcc@13.2.0 languages='c,c++,fortran'
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0
      extra_attributes:
        compilers:
          c: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gcc
          cxx: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/g++
          fortran: /glade/u/apps/common/23.08/spack/opt/spack/gcc/13.2.0/bin/gfortran
    buildable: false
    variants:
    - +piclibs
    - languages=c,c++,fortran,go
    require:
    - '%gcc@7.5.0'
  libfabric:
    externals:
    - spec: libfabric@1.15.2 fabrics=cxi,tcp,udp
      prefix: /opt/cray/libfabric/1.15.2.0
    - spec: libfabric@1.15.0.0
      prefix: /opt/cray/libfabric/1.15.0.0
    buildable: false
    require:
    - '%gcc@7.5.0'
  bash:
    externals:
    - spec: bash@4.4.23
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  cpio:
    externals:
    - spec: cpio@2.13
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  lustre:
    externals:
    - spec: lustre@2.15.2.2_cray_201_ga3f7ea1
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  m4:
    # Julia of course...
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  openssl:
    # Requiring certs=system is necessary to perform builds like rust using
    # external openssl
    externals:
    - spec: openssl@1.1.1l
      prefix: /usr
    buildable: false
    require:
    - certs=system
    - '%gcc@7.5.0'
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
    buildable: false
    require:
    - '%gcc@7.5.0'
  adios2:
    variants:
    - +hdf5
    - ~python
  all:
    'compiler:':
    - gcc@7.5.0
    - gcc
    - oneapi
    - nvhpc
    - cce
    providers:
      'mpi:':
      - cray-mpich
      - impi
      'szip:':
      - libszip
      'pkgconfig:':
      - pkg-config
      'lapack:':
      - openblas
      - intel-oneapi-mkl
      - cray-libsci
      - nvhpc
      'blas:':
      - openblas
      - intel-oneapi-mkl
      - cray-libsci
      - nvhpc
      'zlib-api:':
      - zlib
    permissions:
      read: world
      write: user
    target:
      # This target is lowest-common denominator between Intel and Milans
    - x86_64_v3
    require:
      # This should force packages to use the vendor-preferred solution
      # for BLAS and LAPACK without needing to set it on each package
      # BUT IT MAY ONLY WORK IF ALL ARE AVAILABLE/INSTALLED FIRST!
    - one_of:
      - '%gcc@7 ^openblas %gcc@7'
      - '%gcc@13 ^openblas %gcc@13'
      - '%cce ^cray-libsci'
      - '%oneapi ^intel-oneapi-mkl'
      - '%nvhpc ^nvhpc'
      when: ^blas
    - one_of:
      - '%gcc@7 ^openblas %gcc@7'
      - '%gcc@13 ^openblas %gcc@13'
      - '%cce ^cray-libsci'
      - '%oneapi ^intel-oneapi-mkl'
      - '%nvhpc ^nvhpc'
      when: ^lapack
    - any_of:
      - ^pkg-config
      when: ^pkgconfig
  antlr:
    require: '%gcc@7.5.0'
  aocc:
    require:
    - +license-agreed
  apptainer:
    variants:
    - ~suid
  arpack-ng:
    variants:
    - ~mpi
  autoconf:
    require: '%gcc@7.5.0'
  autoconf-archive:
    require: '%gcc@7.5.0'
  automake:
    require: '%gcc@7.5.0'
  binutils:
    require:
    - '%gcc@7.5.0'
  bison:
    require: '%gcc@7.5.0'
  bzip2:
    require: '%gcc@7.5.0'
  c-blosc:
    require:
    - '%gcc@7.5.0'
  cairo:
    require: '%gcc@7.5.0'
    variants:
    - +X
    - +fc
    - +ft
    - +gobject
    - +pdf
    - +png
  cdo:
    variants:
    - +curl
  charliecloud:
    variants:
    - +squashfuse
  cli11:
    require:
    - '%gcc@7.5.0'
  cmake:
    # Without +ownlibs, some packages can't concretize due to infinite regression
    require: '%gcc@7.5.0'
    variants:
    - +ownlibs
  cp2k:
    variants:
    - +elpa
    - +libvori
    - +plumed
    - +spglib
  cray-libsci:
    externals:
    - spec: cray-libsci@23.02.1.1
      modules:
      - cray-libsci/23.02.1.1
    - spec: cray-libsci@23.09.1.1
      modules:
      - cray-libsci/23.09.1.1
    buildable: false
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.25 %gcc
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/gnu/9.1
    - spec: cray-mpich@8.1.25 %cce
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/cray/10.0
    - spec: cray-mpich@8.1.25 %nvhpc
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/nvidia/20.7
    - spec: cray-mpich@8.1.25 %oneapi
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/intel/19.0
    - spec: cray-mpich@8.1.27 %gcc
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/gnu/9.1
    - spec: cray-mpich@8.1.27 %cce
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/cray/14.0
    - spec: cray-mpich@8.1.27 %nvhpc
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/nvidia/20.7
    - spec: cray-mpich@8.1.27 %oneapi
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/intel/2022.1
    - spec: cray-mpich@8.1.27 %aocc
      prefix: /opt/cray/pe/mpich/8.1.27/ofi/aocc/3.0
    buildable: false
  cuda:
    require:
    - +allow-unsupported-compilers
    - '%gcc@7.5.0'
    externals:
    - spec: cuda@11.8.0
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/cuda/11.8.0
    - spec: cuda@12.2.1
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/cuda/12.2.1
    buildable: false
  cudnn:
    require:
    - '%gcc@7.5.0'
    externals:
    - spec: cudnn@8.7.0.84-11.8
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/cudnn/8.7.0.84-11.8
    buildable: false
  curl:
    # Need mbedtls option for Julia - most other packages seem to prefer openSSL
    require: '%gcc@7.5.0'
    variants:
    - +libidn2
    - +libssh2
    - +nghttp2
    - tls=openssl,mbedtls
  darshan-runtime:
    variants:
    - +parallel-netcdf
    - scheduler=pbs
    require:
    - any_of:
      - ^hdf5+mpi
      when: +hdf5
  darshan-util:
    variants:
    - +bzip2
  doxygen:
    variants:
    - +graphviz
    require:
    - '%gcc@7.5.0'
  ecbuild:
    require:
    - '%gcc@7.5.0'
  eccodes:
    variants:
    - +fortran
    - +netcdf
    - +png
    - +tools
    - jp2k=jasper
  ecflow:
    variants:
    - +ui
  eigen:
    require:
    - '%gcc@7.5.0'
  emacs:
    variants:
    - +X
    - +json
    - +treesitter
    require:
    - any_of:
      - ^gtkplus+cups
      when: +X
  esmf:
    # If external-lapack not forced, concretizer will try to be lazy and
    # avoid lapack requirements by switching to internal despite variant
    require:
    - any_of:
      - '@8.1: +external-lapack'
      - '@:8'
    variants:
    - +parallelio
    - ~mpi
    - ~pnetcdf
    - ~xerces
  expat:
    require: '%gcc@7.5.0'
  ffmpeg:
    variants:
    - +X
    - +drawtext
    - +libaom
    - +libmp3lame
    - +libopenjpeg
    - +libopus
    - +libsnappy
    - +libspeex
    - +libssh
    - +libvorbis
    - +libvpx
    - +libwebp
    - +libx264
    - +libxml2
    - +libzma
    - +libzmq
    - +sdl2
  fftw:
    variants:
    - ~mpi
  flex:
    require: '%gcc@7.5.0'
  fltk:
    require:
    - '%gcc@7.5.0'
  fontconfig:
    require: '%gcc@7.5.0'
  freetype:
    # Newer version leads to concretization issues for Python packages
    # This setting avoids multiple builds of many packages
    require: '@:2.10.2'
  gawk:
    require:
    - '%gcc@7.5.0'
  gdal:
    require:
    - any_of:
      - ^hdf5~mpi
      when: +hdf5
    variants:
    - +blosc
    - +curl
    - +deflate
    - +expat
    - +geos
    - +gif
    - +grass
    - +grib
    - +hdf5
    - +iconv
    - +jasper
    - +jpeg
    - +libcsf
    - +liblzma
    - +lz4
    - +netcdf
    - +pcidsk
    - +png
    - +qhull
    - +sqlite3
    - +zstd
  gdb:
    variants:
    - +gold
    - +ld
    - +lto
    - +tui
    - ~debuginfod
    - ~python
  giflib:
    require:
    - '%gcc@7.5.0'
  git:
    variants:
    - +svn
    - +tcltk
  glpk:
    require:
    - '%gcc@7.5.0'
  gmp:
    require:
    - '%gcc@7.5.0'
  gmt:
    variants:
    - +ffmpeg
    - +fftw
    - +geos
    - +ghostscript
    - +glib
    - +pcre
    - ~graphicsmagick
    require:
    - +blas
    - +lapack
  gnuplot:
    variants:
    - +X
    - +qt
    - +wx
  googletest:
    require: '%gcc@7.5.0'
  gptl:
    variants:
    - +papi
    - +pmpi
  grads:
    variants:
    - +dap
  groff:
    require:
    - '%gcc@7.5.0'
  gtkplus:
    variants:
    - +cups
  harfbuzz:
    variants:
    - +graphite2
  hdf:
    variants:
    - +fortran
    - +szip
  hdf5:
    variants:
    - +cxx
    - +fortran
    - +hl
    - +szip
    - ~mpi
  hwloc:
    require: '%gcc@7.5.0'
    variants:
    - +cuda
  icu4c:
    require: '%gcc@7.5.0'
  idl:
    require:
    - '%gcc@7.5.0'
  imagemagick:
    variants:
    - +ghostscript
  intel-oneapi-compilers:
    require:
    - '%gcc@7.5.0'
    externals:
    - spec: intel-oneapi-compilers@2024.0.2
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-compilers/2024.0.2
    buildable: false
  intel-oneapi-inspector:
    require:
    - '%gcc@7.5.0'
    externals:
    - spec: intel-oneapi-inspector@2024.0.0
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/intel-oneapi-inspector/2024.0.0
    buildable: false
  intel-oneapi-mpi:
    variants:
    - +external-libfabric
    - +generic-names
  ispc:
    require: '%clang'
  jasper:
    # Newer Jasper versions have caused issues in the past
    # TODO - recheck whether this is a problem now
    require:
    - '%gcc@7.5.0'
    - '@:2'
  json-c:
    require:
    - '%gcc@7.5.0'
  jsoncpp:
    require:
    - '%gcc@7.5.0'
  julia:
    require: ^llvm~clang~gold~polly ^openblas threads=openmp
  krb5:
    require:
    - '%gcc@7.5.0'
  libaec:
    require:
    - '%gcc@7.5.0'
  libarchive:
    require: compression=bz2lib,lz4,lzma,lzo2,zlib,zstd xar=expat
  libcatalyst:
    require:
    - '%gcc@7.5.0'
  libdeflate:
    require:
    - '%gcc@7.5.0'
  libffi:
    require:
    - '@:3.3'
    - '%gcc@7.5.0'
  libfuse:
    require: ~utils
  libgd:
    # gnuplot fails to build with newer version due to libiconv linking failure
    require: '@2.2.4'
  libgit2:
    # Julia is demanding...
    require:
    - '@1.5'
  libjpeg-turbo:
    require: '%gcc@7.5.0'
  libogg:
    require:
    - '%gcc@7.5.0'
  libpciaccess:
    require:
    - '%gcc@7.5.0'
  libpng:
    require: '%gcc@7.5.0'
  libssh2:
    # Julia again...
    require:
    - '@1.10'
    variants:
    - crypto=mbedtls
  libszip:
    require: '%gcc@7.5.0'
  libtheora:
    require:
    - '%gcc@7.5.0'
  libtiff:
    require: '%gcc@7.5.0'
  libtirpc:
    require:
    - '%gcc@7.5.0'
  libtool:
    require: '%gcc@7.5.0'
  libunwind:
    require: '%gcc@7.5.0'
    variants:
    - +cxx_exceptions
    - +debug_frame
    - +pic
    - +xz
    - +zlib
    - components=setjump,ptrace,coredump
  libx11:
    require:
    - '%gcc@7.5.0'
  libxaw:
    require:
    - '%gcc@7.5.0'
  libxcb:
    require: '%gcc@7.5.0'
  libxcrypt:
    require:
    - '%gcc@7.5.0'
  libxml2:
    require: '%gcc@7.5.0'
  linaro-forge:
    require:
    - '%gcc@7.5.0'
    externals:
    - spec: linaro-forge@23.1
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/linaro-forge/23.1
    buildable: false
  lz4:
    require:
    - '%gcc@7.5.0'
  matlab:
    require:
    - '%gcc@7.5.0'
  maven:
    require:
    - '%gcc@7.5.0'
  mbedtls:
    # Julia of course...
    require:
    - '@2.28'
    - libs=static,shared
  met:
    variants:
    - +graphics
    - +grib2
    - +lidar2nc
    - +modis
    - +python
  metplus:
    variants:
    - +cycloneplotter
    - +makeplots
    - +plotdataplane
    - +series_analysis
  mgard:
    require:
    - '%gcc@7.5.0'
  miniconda3:
    externals:
    - spec: miniconda3@4.12.0
      prefix: /glade/u/apps/opt/conda
    buildable: false
  motif:
    require:
    - ^autoconf@2.69
  mpich:
    require:
    - device=ch4
    - netmod=ofi
    - pmi=pmi2
    variants:
    - ~cuda
  mpifileutils:
    variants:
    - +gpfs
    - +lustre
    - +xattr
  mvapich:
    variants:
    - file_systems=lustre,gpfs,nfs,ufs
    - process_managers=auto
    require:
    - netmod=ofi
    - +pbs
    - one_of:
      - ~cuda
      when: '%oneapi'
    - one_of:
      - +cuda
      when: '%nvhpc'
  ncl:
    # Newer ESMF versions cause issues for NCL
    # TODO - bake this into recipe?
    require:
    - ^esmf@:8.0.1 ~external-lapack
    - ^hdf5~mpi
    - '%gcc@7.5.0'
    variants:
    - +eemd
    - +gdal
    - +grib
    - +hdf-eos2
    - +hdf-eos5
    - +hdf4
  netcdf:
    variants:
    - +dap
    - ~mpi
  netcdf-c:
    variants:
    - +dap
    - ~mpi
  netcdf-cxx4:
    variants:
    - ~doxygen
  nghttp2:
    # Thanks Julia...
    require: '@1.48'
  ninja:
    require:
    - '%gcc@7.5.0'
  numactl:
    require:
    - '%gcc@7.5.0'
  nvhpc:
    require:
    - '%gcc@7.5.0'
    externals:
    - spec: nvhpc@24.1
      prefix: /glade/u/apps/common/23.08/spack/opt/spack/nvhpc/24.1
    buildable: false
  octave:
    variants:
    - +arpack
    - +curl
    - +fftw
    - +fltk
    - +fontconfig
    - +freetype
    - +gl2ps
    - +glpk
    - +gnuplot
    - +llvm
    - +magick
    - +opengl
    - +qhull
    - +qrupdate
    - +qscintilla
    - +qt
    - +suitesparse
    - +zlib
  openblas:
    variants:
    - +fortran
    - threads=openmp
  openjdk:
    require:
    - '%gcc@7.5.0'
  openmpi:
    require:
    - fabrics=cma,ofi
    - schedulers=tm
    - +gpfs
    - +lustre
    - +internal-pmix
    - +cuda
    - any_of:
      - '^cuda@12.2:'
      when: '@5.0.0rc16 +cuda'
  openpbs:
    externals:
    - spec: openpbs@2021.1.3
      prefix: /opt/pbs
    buildable: false
    require:
    - '%gcc@7.5.0'
  openssh:
    require:
    - '%gcc@7.5.0'
  osu-micro-benchmarks:
    variants:
    - +cuda
  pango:
    variants:
    - +X
  parallelio:
    variants:
    - +ncint
    - +pnetcdf
    - ~logging
    require:
    - any_of:
      - ~pnetcdf
      when: ~mpi
  parallelio1:
    variants:
    - +pnetcdf
  patchelf:
    # Patchelf 0.18 breaks using gcc@7.5.0
    require:
    - '@:0.17'
  pcre:
    require:
    - '%gcc@7.5.0'
  pcre2:
    require: '%gcc@7.5.0'
  pegtl:
    require:
    - '%gcc@7.5.0'
  perl:
    require: '%gcc@7.5.0'
  pmix:
    require:
    - '%gcc@7.5.0'
  protobuf:
    require:
    - '%gcc@7.5.0'
  py-fypp:
    require:
    - '%gcc@7.5.0'
  py-netcdf4:
    variants:
    - ~mpi
  py-numpy:
    # TODO - force use of non-Julia openblas, but next time build it first
    require:
    - any_of:
      - ^openblas symbol_suffix=none
      when: ^openblas
  py-setuptools:
    # Newer versions cannot be used by py-numpy as of Aug 2023
    require:
    - '@:63'
  qhull:
    require:
    - '%gcc@7.5.0'
  qt:
    variants:
    - +dbus
    - +examples
    - +gtk
    - +opengl
    - +webkit
  readline:
    require: '%gcc@7.5.0'
  rstudio:
    require:
    - '%gcc@7.5.0'
  rsync:
    require:
    - '%gcc@7.5.0'
  sed:
    require:
    - '%gcc@7.5.0'
  singularityce:
    variants:
    - ~suid
  snappy:
    require:
    - '%gcc@7.5.0'
  sqlite:
    require: '%gcc@7.5.0'
  superlu-dist:
    variants:
    - +openmp
  sz:
    require:
    - '%gcc@7.5.0'
  texinfo:
    require: '%gcc@7.5.0'
  texlive:
    require:
    - '%gcc@7.5.0'
  ucx:
    require:
    - '%gcc@7.5.0'
  util-linux-uuid:
    require: '%gcc@7.5.0'
  vim:
    variants:
    - +cscope
    - +gtk
    - +gui
    - +lua
    - +perl
    - +python
    - +ruby
    - +x
    - features=huge
    require:
    - any_of:
      - ^gtkplus+cups
      when: +gtk
  vtk-m:
    require:
    - '%gcc@7.5.0'
  wget:
    require:
    - '%gcc@7.5.0'
  wgrib2:
    variants:
    - +netcdf4
    - +proj4
    - +udf
    - ~checks
    - ~netcdf3
  which:
    require: '%gcc@7.5.0'
  wxwidgets:
    variants:
    - +opengl
  xz:
    require: '%gcc@7.5.0'
  zfp:
    require:
    - '%gcc@7.5.0'
  zlib:
    # zlib 1.3 causes configure failure for openssh because it expects
    # 3 version digits (i.e., X.Y.Z) as of Aug 2023
    require:
    - '%gcc@7.5.0'
    - '@:1.2.13'
  zstd:
    require: '%gcc@7.5.0'
    variants:
    - +programs
